language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - wget http://getcomposer.org/composer.phar
  - php -d memory_limit=-1 composer.phar require symfony/symfony:${SYMFONY_VERSION}
  - php -d memory_limit=-1 composer.phar install
  - phpunit