language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist

script: phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true