language: php

php:
  - 5.6
  - 7.0

before_install:
  - wget http://getcomposer.org/composer.phar

install: php -d memory_limit=-1 composer.phar install --no-interaction --prefer-source

script:
  - phpunit --coverage-text